name: deploy-pages

on:
  push:
    branches:
      - deploy-pages
      - master

jobs:
  main:
    name: Deploy to ghpages

    runs-on: ubuntu-latest

    steps:
        # Clone repo + submodules
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: main

      - name: Checkout ghpages repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: gh-pages
          path: gh-pages

      - name: Install DMD
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build HTML
        shell: bash
        run: |
          cd main
          dub upgrade
          dub build -b ddox -v
          ./DGrammar/generate_html_from_libdparse.sh
          cp ./DGrammar/grammar.html docs/grammar.html
          cp -r docs/* ../gh-pages
          cd ../gh-pages

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          repository: gh-pages
